<?php
/**
 * Creates and finalises a package directory.
 *
 * @package NewfoldLabs\WP\SiteMigrator
 */

namespace NewfoldLabs\WP\SiteMigrator\Core\Package;

/**
 * Owns the package directory layout.
 *
 * Nothing else should build paths inside a package by hand; ask this class for them.
 */
class PackageWriter {

	const PARTS_DIR = 'parts';
	const LARGE_DIR = 'large';
	const LISTS_DIR = '.lists';

	/**
	 * Absolute package directory.
	 *
	 * @var string
	 */
	protected $dir;

	/**
	 * Constructor.
	 *
	 * @param string $dir Absolute package directory.
	 */
	public function __construct( $dir ) {
		$this->dir = \rtrim( $dir, '/\\' );
	}

	/**
	 * Create the directory skeleton.
	 *
	 * @return void
	 *
	 * @throws \RuntimeException If a directory cannot be created.
	 */
	public function prepare() {
		$dirs = array(
			$this->dir,
			$this->path( self::PARTS_DIR ),
			$this->path( self::LARGE_DIR ),
			$this->path( self::LISTS_DIR ),
		);

		foreach ( $dirs as $dir ) {
			if ( ! \is_dir( $dir ) && ! \wp_mkdir_p( $dir ) ) {
				throw new \RuntimeException( \esc_html( 'Unable to create package directory: ' . $dir ) );
			}
		}

		$this->protect();
	}

	/**
	 * Deny web access to the package directory.
	 *
	 * A package contains the entire site database. It must never be fetchable over HTTP, and the
	 * previous storage directory had only an index.php silence file, with archive names derived
	 * from uniqid() (finding 2.4).
	 *
	 * @return void
	 */
	protected function protect() {
		$index = $this->path( 'index.php' );

		if ( ! \file_exists( $index ) ) {
			\file_put_contents( $index, "<?php\n// Silence is golden.\n" ); // phpcs:ignore WordPress.WP.AlternativeFunctions
		}

		$htaccess = $this->path( '.htaccess' );

		if ( ! \file_exists( $htaccess ) ) {
			$rules = "# Generated by nfd-site-migrator. Do not edit.\n"
				. "<IfModule mod_authz_core.c>\n\tRequire all denied\n</IfModule>\n"
				. "<IfModule !mod_authz_core.c>\n\tOrder allow,deny\n\tDeny from all\n</IfModule>\n";

			\file_put_contents( $htaccess, $rules ); // phpcs:ignore WordPress.WP.AlternativeFunctions
		}

		$webconfig = $this->path( 'web.config' );

		if ( ! \file_exists( $webconfig ) ) {
			$xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<configuration>\n\t<system.webServer>\n"
				. "\t\t<authorization>\n\t\t\t<deny users=\"*\" />\n\t\t</authorization>\n"
				. "\t</system.webServer>\n</configuration>\n";

			\file_put_contents( $webconfig, $xml ); // phpcs:ignore WordPress.WP.AlternativeFunctions
		}
	}

	/**
	 * Absolute path to something inside the package.
	 *
	 * @param string $relative Relative path.
	 *
	 * @return string
	 */
	public function path( $relative = '' ) {
		if ( '' === $relative ) {
			return $this->dir;
		}

		return $this->dir . DIRECTORY_SEPARATOR . \ltrim( $relative, '/\\' );
	}

	/**
	 * Package directory.
	 *
	 * @return string
	 */
	public function dir() {
		return $this->dir;
	}

	/**
	 * Relative path of a part volume.
	 *
	 * A part that fits in one volume gets no numeric suffix.
	 *
	 * @param string $part   Part name.
	 * @param int    $volume Volume number, from 1.
	 *
	 * @return string
	 */
	public function part_relative( $part, $volume = 1 ) {
		if ( $volume > 1 ) {
			return self::PARTS_DIR . '/' . $part . '.' . \str_pad( $volume, 3, '0', STR_PAD_LEFT ) . '.zip';
		}

		return self::PARTS_DIR . '/' . $part . '.zip';
	}

	/**
	 * Absolute path of a part volume.
	 *
	 * @param string $part   Part name.
	 * @param int    $volume Volume number, from 1.
	 *
	 * @return string
	 */
	public function part_path( $part, $volume = 1 ) {
		return $this->path( $this->part_relative( $part, $volume ) );
	}

	/**
	 * Absolute path of a part's transient file list.
	 *
	 * @param string $part Part name.
	 *
	 * @return string
	 */
	public function list_path( $part ) {
		return $this->path( self::LISTS_DIR . '/' . $part . '.list' );
	}

	/**
	 * Absolute path of a loosely stored large file.
	 *
	 * @param string $relative Path relative to the WordPress install.
	 *
	 * @return string
	 */
	public function large_path( $relative ) {
		return $this->path( self::LARGE_DIR . '/' . \ltrim( $relative, '/' ) );
	}

	/**
	 * SHA-256 of a file inside the package.
	 *
	 * @param string $relative Relative path.
	 *
	 * @return string Empty when the file is missing.
	 */
	public function checksum( $relative ) {
		$path = $this->path( $relative );

		if ( ! \is_readable( $path ) ) {
			return '';
		}

		return \hash_file( 'sha256', $path );
	}

	/**
	 * Size of a file inside the package.
	 *
	 * @param string $relative Relative path.
	 *
	 * @return int
	 */
	public function size( $relative ) {
		$path = $this->path( $relative );

		return \is_readable( $path ) ? (int) \filesize( $path ) : 0;
	}

	/**
	 * Write the manifest and remove transient run state.
	 *
	 * The manifest goes last: its presence is the signal that the package is complete.
	 *
	 * @param Manifest $manifest Completed manifest.
	 *
	 * @return string Absolute path to the manifest.
	 */
	public function finalize( Manifest $manifest ) {
		$manifest->recalculate_totals();
		$path = $manifest->write( $this->dir );

		\nfd_sm_delete_directory( $this->path( self::LISTS_DIR ) );

		$checkpoint = new Checkpoint( $this->dir );
		$checkpoint->clear();

		return $path;
	}
}
