<?php

/**
 * Function to open a file and throw an error when not possible
 *
 * @param string $file Path to the file to open
 * @param string $mode Mode in which to open the file
 *
 * @return resource
 *
 * @throws \Exception When we are unable to open the file.
 */
function nfd_sm_open( $file, $mode ) {
	$file_handle = fopen( $file, $mode );
	if ( false === $file_handle ) {
		throw new \Exception(
			sprintf( 'Unable to open %s with mode %s.', esc_xml( $file ), esc_xml( $mode ) )
		);
	}

	return $file_handle;
}

/**
 * Write contents to a file
 *
 * @param resource $handle  File handle to write to
 * @param string   $content Contents to write to the file
 *
 * @return integer
 *
 * @throws \Exception If unable to write.
 */
function nfd_sm_write( $handle, $content ) {
	$write_result = fwrite( $handle, $content );
	if ( false === $write_result ) {
		$meta = stream_get_meta_data( $handle );
		if ( $meta ) {
			throw new \Exception( sprintf( 'Unable to write to: %s.', esc_xml( $meta['uri'] ) ) );
		}
	} elseif ( null === $write_result ) {
		return strlen( $content );
	} elseif ( strlen( $content ) !== $write_result ) {
		$meta = stream_get_meta_data( $handle );
		if ( $meta ) {
			throw new \Exception( sprintf( 'Out of disk space. Unable to write to: %s', esc_xml( $meta['uri'] ) ) );
		}
	}

	return $write_result;
}

/**
 * Check whether blog ID is main site
 *
 * @param  integer $blog_id Blog ID
 * @return boolean
 */
function nfd_sm_is_mainsite( $blog_id = null ) {
	return null === $blog_id || 0 === $blog_id || 1 === $blog_id;
}

/**
 * Get WordPress table prefix by blog ID
 *
 * @param  integer $blog_id Blog ID
 * @return string
 */
function nfd_sm_table_prefix( $blog_id = null ) {
	global $wpdb;

	// Set base table prefix
	if ( nfd_sm_is_mainsite( $blog_id ) ) {
		return $wpdb->base_prefix;
	}

	return $wpdb->base_prefix . $blog_id . '_';
}

/**
 * Get the base storage directory
 */
function nfd_sm_storage_path() {
	static $protected = false;

	$uploads   = wp_get_upload_dir();
	$directory = $uploads['basedir'] . DIRECTORY_SEPARATOR . 'nfd-site-migrator' . DIRECTORY_SEPARATOR;
	wp_mkdir_p( $directory );

	// Protected at the root, not only in the directories that happen to hold a package. The
	// package and staging directories wrote their own rules and `import/` did not, so an import
	// checkpoint -- absolute server paths, the table prefix, every plugin and theme the import
	// installed -- was fetchable over HTTP on Apache. Once per request: the guards below are
	// three stat calls, and this function is called often.
	if ( ! $protected ) {
		$protected = true;

		nfd_sm_protect_directory( $directory );
	}

	return $directory;
}

/**
 * Deny web access to a directory, as far as the server allows.
 *
 * Three files, because three servers. `index.php` stops a directory listing anywhere; `.htaccess`
 * is Apache; `web.config` is IIS. **nginx reads none of them** and cannot be configured from
 * inside the document root at all -- which is why `Checker::check_storage_reachable()` goes on to
 * *ask* whether the directory is reachable rather than trusting that writing these was enough.
 *
 * @param string $directory Absolute path.
 *
 * @return void
 */
function nfd_sm_protect_directory( $directory ) {
	$directory = rtrim( $directory, '/\\' ) . DIRECTORY_SEPARATOR;

	$files = array(
		'index.php'  => "<?php\n// Silence is golden.\n",
		'.htaccess'  => "# Generated by nfd-site-migrator. Do not edit.\n"
			. "<IfModule mod_authz_core.c>\n\tRequire all denied\n</IfModule>\n"
			. "<IfModule !mod_authz_core.c>\n\tOrder allow,deny\n\tDeny from all\n</IfModule>\n",
		'web.config' => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<configuration>\n\t<system.webServer>\n"
			. "\t\t<authorization>\n\t\t\t<deny users=\"*\" />\n\t\t</authorization>\n"
			. "\t</system.webServer>\n</configuration>\n",
	);

	foreach ( $files as $name => $contents ) {
		$path = $directory . $name;

		if ( ! file_exists( $path ) ) {
			file_put_contents( $path, $contents ); // phpcs:ignore WordPress.WP.AlternativeFunctions
		}
	}
}

/**
 * The two shapes another site's REST API can have, best guess first.
 *
 * A site with pretty permalinks serves both; a site without them serves only `?rest_route=`, and
 * answers `/wp-json/…` with a redirect to its home page — HTML, which reads as "the plugin is not
 * installed there" (finding 3.17). Plain permalinks are the default on a fresh install and common
 * on exactly the hosts this plugin exists for, so the query form goes first and the path form
 * stays as a fallback for a host that blocks it.
 *
 * Two callers now depend on getting this right — the pairing handshake and the direct transfer —
 * and the transfer makes hundreds of requests, so it settles on one base and reuses it rather
 * than rediscovering this per file.
 *
 * @param string $site_url Another site's address.
 *
 * @return array Base URLs, each ending in the namespace separator.
 */
function nfd_sm_rest_bases( $site_url ) {
	$base = trailingslashit( esc_url_raw( trim( (string) $site_url ) ) );

	if ( '/' === $base ) {
		return array();
	}

	return array(
		$base . '?rest_route=/nfd-site-migrator/v1/',
		$base . 'wp-json/nfd-site-migrator/v1/',
	);
}

/**
 * Build a URL for a route below one of those bases.
 *
 * The separator is the whole point. With the path form, query arguments start with `?`; with the
 * query form the route is *already* a query argument and a second `?` gets swallowed into the
 * value of the first, so the route stops resolving.
 *
 * @param string $base  A base from nfd_sm_rest_bases().
 * @param string $route Route below the namespace, e.g. `transfer/file`.
 * @param array  $args  Query arguments.
 *
 * @return string
 */
function nfd_sm_rest_url( $base, $route, $args = array() ) {
	$url = rtrim( (string) $base, '/' ) . '/' . ltrim( (string) $route, '/' );

	if ( empty( $args ) ) {
		return $url;
	}

	return $url . ( false === strpos( $url, '?' ) ? '?' : '&' ) . http_build_query( $args );
}

/**
 * The plugin's mark, as an admin-menu icon.
 *
 * The same logo the masthead draws, in the one form the admin menu accepts. Keep the geometry
 * here and in `src/components/Masthead.js` identical -- `MarkTest` asserts they are, because two
 * hand-maintained copies of a path are two logos waiting to drift apart.
 *
 * It is drawn as a **knockout**: the tile is painted and the glyph is a hole through it. That is
 * not a stylistic choice. WordPress applies its hover and current-item opacity to `<img>` menu
 * icons only, and a base64 SVG becomes a CSS `background-image` instead -- so this icon gets no
 * state change from WordPress at all, whatever colour it is drawn in. A hole shows the menu item's
 * own background, which *does* change on hover and when the page is current, so the mark picks up
 * the states WordPress will not give it.
 *
 * The tile is `#a7aaad`, the colour wp-admin rests its own menu icons at, so it sits at the same
 * weight as the dashicons above and below it.
 *
 * @return string A `data:image/svg+xml;base64,` URI.
 */
function nfd_sm_menu_icon() {
	$glyph = '<g fill="none" stroke="#000" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">'
		. '<rect x="15.8" y="10.5" width="10.4" height="11" rx="2.9"/>'
		. '<path d="M15.8 15.1h10.4"/>'
		. '<path d="M7.6 13.2h5M5.4 18.8h7"/>'
		. '</g>';

	$svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">'
		. '<mask id="nfd-sm-mark">'
		. '<rect width="32" height="32" rx="9" fill="#fff"/>'
		. $glyph
		. '</mask>'
		. '<rect width="32" height="32" rx="9" fill="#a7aaad" mask="url(#nfd-sm-mark)"/>'
		. '</svg>';

	// phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_encode -- what the menu API takes.
	return 'data:image/svg+xml;base64,' . base64_encode( $svg );
}

/**
 * Where this site keeps the package it exported.
 *
 * One place, because two now ask: the browser downloads parts out of it and a paired destination
 * pulls them straight from it. A second literal `storage . 'package'` somewhere is how the
 * transfer ends up serving a directory the export never wrote to.
 *
 * @return string Absolute path, no trailing separator.
 */
function nfd_sm_package_path() {
	return rtrim( nfd_sm_storage_path(), '/\\' ) . DIRECTORY_SEPARATOR . 'package';
}

/**
 * Measure a directory, with a time budget and a cache.
 *
 * Walking a large uploads directory is slow — several seconds for a few gigabytes, minutes for
 * tens — and preflight runs on a page load. So the result is cached, and the walk gives up when
 * the budget runs out and says so rather than blocking the request indefinitely.
 *
 * @param string $path   Absolute directory.
 * @param float  $budget Seconds to spend, or 0 for no limit.
 *
 * @return array `bytes`, `files`, and `complete` — false when the budget ran out.
 */
function nfd_sm_measure_dir( $path, $budget = 3.0 ) {
	$path = realpath( $path );

	if ( ! $path || ! is_dir( $path ) ) {
		return array(
			'bytes'    => 0,
			'files'    => 0,
			'complete' => true,
		);
	}

	$key    = 'nfd_sm_dirsize_' . md5( $path );
	$cached = get_transient( $key );

	if ( is_array( $cached ) ) {
		return $cached;
	}

	$deadline = $budget > 0 ? microtime( true ) + $budget : 0;
	$bytes    = 0;
	$files    = 0;
	$complete = true;

	$iterator = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $path, FilesystemIterator::SKIP_DOTS ),
		RecursiveIteratorIterator::LEAVES_ONLY,
		RecursiveIteratorIterator::CATCH_GET_CHILD
	);

	foreach ( $iterator as $item ) {
		if ( ! $item->isFile() ) {
			continue;
		}

		$bytes += (int) $item->getSize();
		++$files;

		// Checking the clock on every file would itself be a cost; every 512 is plenty.
		if ( $deadline > 0 && 0 === ( $files % 512 ) && microtime( true ) >= $deadline ) {
			$complete = false;
			break;
		}
	}

	$result = array(
		'bytes'    => $bytes,
		'files'    => $files,
		'complete' => $complete,
	);

	// A partial measurement is worth caching too, briefly: it stops every request paying the
	// same budget, and it is refreshed often enough to stay useful.
	set_transient( $key, $result, $complete ? 900 : 120 );

	return $result;
}

/**
 * Size of a directory in bytes.
 *
 * @param string $path Absolute directory.
 *
 * @return int
 */
function nfd_sm_get_dir_size( $path ) {
	$measured = nfd_sm_measure_dir( $path, 0 );

	return $measured['bytes'];
}

/**
 * Get a value from an object or an array.  Allows the ability to fetch a nested value from a
 * heterogeneous multidimensional collection using dot notation.
 *
 * @param array|object $data        Data to fetch from.
 * @param string       $key         Key as a string, optionally using dot notation.
 * @param mixed        $default_val The fallback value if a value doesn't exist.
 *
 * @return mixed
 */
function nfd_sm_data_get( $data, $key, $default_val = null ) {
	$value = $default_val;
	if ( is_array( $data ) && array_key_exists( $key, $data ) ) {
		$value = $data[ $key ];
	} elseif ( is_object( $data ) && property_exists( $data, $key ) ) {
		$value = $data->$key;
	} else {
		$segments = explode( '.', $key );
		foreach ( $segments as $segment ) {
			if ( is_array( $data ) && array_key_exists( $segment, $data ) ) {
				$value = $data = $data[ $segment ]; // phpcs:ignore
			} elseif ( is_object( $data ) && property_exists( $data, $segment ) ) {
				$value = $data = $data->$segment; // phpcs:ignore
			} else {
				$value = $default_val;
				break;
			}
		}
	}

	return $value;
}

/**
 * Get WordPress plugins directory
 *
 * @return string
 */
function nfd_sm_plugins_dir() {
	return untrailingslashit( WP_PLUGIN_DIR );
}

/**
 * Get WordPress themes directory
 *
 * @return array
 */
function nfd_sm_themes_dir() {
	$theme_dirs = array();
	foreach ( search_theme_directories() as $theme_name => $theme_info ) {
		if ( isset( $theme_info['theme_root'] ) ) {
			if ( ! in_array( $theme_info['theme_root'], $theme_dirs, true ) ) {
				$theme_dirs[] = untrailingslashit( $theme_info['theme_root'] );
			}
		}
	}

	return $theme_dirs;
}

/**
 * Get WordPress uploads directory
 *
 * @return string
 */
function nfd_sm_uploads_dir() {
	$upload_dir = wp_upload_dir();
	if ( $upload_dir ) {
		if ( isset( $upload_dir['basedir'] ) ) {
			return untrailingslashit( $upload_dir['basedir'] );
		}
	}
}

/**
 * Get the mu plugins directory for WordPress
 *
 * @return string
 */
function nfd_sm_mu_plugins_dir() {
	$mu_plugins_dir = WPMU_PLUGIN_DIR;
	if ( is_dir( $mu_plugins_dir ) ) {
		return untrailingslashit( $mu_plugins_dir );
	}
}

/**
 * A function to recursively purge a directory
 *
 * @param string $dir The directory path.
 */
function nfd_sm_delete_directory( $dir ) {
	if ( ! is_dir( $dir ) ) {
		return false;
	}

	$files = scandir( $dir );
	foreach ( $files as $file ) {
		if ( '.' !== $file && '..' !== $file ) {
			$path = $dir . '/' . $file;
			if ( is_dir( $path ) ) {
				nfd_sm_delete_directory( $path ); // Recursively delete subdirectories
			} else {
				unlink( $path ); // Delete individual files
			}
		}
	}

	return rmdir( $dir ); // Remove the empty directory
}

/**
 * Whether an import is under way, or finished and still awaiting a decision.
 *
 * The thing this protects is the ability to undo. A finished-but-undecided run's `nfdold_` backup
 * tables are the only copy of this site as it was, and `Importer::rollback()` reads the checkpoint
 * on disk to know what to put back -- so deleting the state directory leaves the tables orphaned
 * and the site with no way to return to itself. A run still in flight is worse: it may be one
 * statement short of the swap.
 *
 * Deliberately narrow. A source that has merely exported has a package and nothing at stake in the
 * database; deleting a plugin is a deliberate act and taking its files with it is what deleting
 * means. Being unable to reverse a migration is a different order of loss.
 *
 * @return bool
 */
function nfd_sm_import_unsettled() {
	if ( ! class_exists( '\\NewfoldLabs\\WP\\SiteMigrator\\Core\\Import\\ImportCheckpoint' ) ) {
		return false;
	}

	$checkpoint = new \NewfoldLabs\WP\SiteMigrator\Core\Import\ImportCheckpoint();

	if ( ! $checkpoint->exists() ) {
		return false;
	}

	return ! \NewfoldLabs\WP\SiteMigrator\Core\Import\ImportCheckpoint::is_settled( $checkpoint->load() );
}

/**
 * Forget what a reactivation can work out again.
 *
 * This is all deactivation does, and the restraint is the point. It used to run
 * `nfd_sm_purge_all()`, which recursively deletes the storage directory -- so switching the plugin
 * off to check whether it was causing something destroyed the package the user had just spent an
 * hour building, with no warning and nothing to undo it. Deactivating is the routine "turn
 * everything off and find the conflict" move; WordPress asks a plugin to make it reversible, and
 * removing data belongs in `uninstall.php`.
 *
 * The worse case was a destination mid-import. The same call deleted `import/`, and with it the
 * checkpoint `Importer::rollback()` needs -- leaving a swapped site, orphaned backup tables, and
 * no way for the plugin to put it back.
 *
 * @return void
 */
function nfd_sm_flush_state() {
	delete_transient( NFD_SM_CAN_MIGRATE_TRANSIENT );
}

/**
 * Everything deleting this plugin should take with it.
 *
 * Split out of `uninstall.php` so it can be tested, and so the multisite branch below has
 * somewhere to live that is not a bare script.
 *
 * **On a network, every site has its own.** `wp_get_upload_dir()` follows `switch_to_blog()`, so a
 * network-activated plugin leaves a storage directory and an options row on each site rather than
 * one of each on the network. Migration itself is blocked at preflight on multisite, so what is
 * left behind is an empty protected directory and a row of defaults — small, but leftover data is
 * leftover data, and the same loop that removes it is the loop that would remove a real package if
 * multisite ever becomes supported.
 *
 * A large network is skipped rather than iterated. WordPress stops counting sites past
 * `wp_is_large_network()` for the same reason this stops deleting past it: a loop long enough to
 * exhaust the request leaves the uninstall half-done, and a half-purged network is worse than an
 * untouched one. On such a network the directories can be removed with `wp site-migrator` gone and
 * a filesystem sweep, which is a thing an administrator of ten thousand sites can do and a plugin
 * being deleted cannot.
 *
 * @return void
 */
function nfd_sm_uninstall() {
	if ( ! is_multisite() ) {
		if ( ! nfd_sm_import_unsettled() ) {
			nfd_sm_purge_all();
		}

		return;
	}

	if ( wp_is_large_network( 'sites' ) ) {
		return;
	}

	// `number => 0` is load-bearing. `WP_Site_Query` defaults to **100**, so the obvious call
	// purges the first hundred sites of a network and leaves the rest -- which is precisely the
	// half-purged state the guard above exists to avoid, arrived at by a default rather than by a
	// timeout. Any network between 101 sites and `wp_is_large_network()` hits it.
	$sites = get_sites(
		array(
			'fields' => 'ids',
			'number' => 0,
		)
	);

	foreach ( $sites as $site_id ) {
		switch_to_blog( (int) $site_id );

		try {
			// Asked per site, because the answer is per site: the checkpoint lives under that
			// site's own uploads directory.
			if ( ! nfd_sm_import_unsettled() ) {
				nfd_sm_purge_all();
			}
		} finally {
			// A network left switched to the wrong site is a strange thing to hand back to
			// whatever runs next, and one throw from a future change is all it would take.
			restore_current_blog();
		}
	}
}

/**
 * Purge Migration related things
 */
function nfd_sm_purge_all() {
	// Delete the options
	foreach ( NFD_SM_OPTIONS_LIST as $option ) {
		delete_option( $option );
	}

	// Delete the migration data
	nfd_sm_delete_directory( nfd_sm_storage_path() );

	// Delete the transient
	delete_transient( NFD_SM_CAN_MIGRATE_TRANSIENT );
}

/**
 * Express a path relative to a root directory, with forward slashes.
 *
 * @param string $root Absolute root directory.
 * @param string $path Absolute path inside the root.
 *
 * @return string Relative path, or the basename when $path is not below $root.
 */
function nfd_sm_relative_path( $root, $path ) {
	$root = rtrim( str_replace( '\\', '/', $root ), '/' ) . '/';
	$path = str_replace( '\\', '/', $path );

	if ( 0 === strpos( $path, $root ) ) {
		return substr( $path, strlen( $root ) );
	}

	return basename( $path );
}

/**
 * Absolute path to this plugin's main file, with symlinks resolved.
 *
 * @return string
 */
function nfd_sm_plugin_file() {
	return NFD_SM_PLUGIN_DIR . NFD_SM_PLUGIN_NAME . '.php';
}

/**
 * How WordPress addresses this plugin in `active_plugins`: `directory/file.php`.
 *
 * Not `NFD_SM_PLUGIN_NAME . '/' . NFD_SM_PLUGIN_NAME . '.php'`, which is a guess that is wrong
 * whenever the directory is not named after the slug — a checkout under its repository name, a
 * Composer or Bedrock deployment, or a symlink into a working copy. Writing the guess into
 * `active_plugins` activates nothing, because there is no file at that path; `Fixups` then
 * deactivates it again as missing, and the plugin is left loaded only by the import loader, at
 * which point `plugin_dir_url()` cannot express its own directory as a URL and every asset
 * 404s. That is a blank admin page on the screen where the user decides whether to keep the
 * migration.
 *
 * `plugin_basename()` answers correctly whenever WordPress has been told about the symlink,
 * which it is for anything in `active_plugins` — but *not* for a plugin loaded from
 * `mu-plugins`, which is exactly the situation during an import. So the answer is checked
 * against the filesystem, and when it does not hold up the plugins directory is searched for
 * the entry that resolves to this one.
 *
 * @return string
 */
function nfd_sm_plugin_basename() {
	static $basename = null;

	if ( null !== $basename ) {
		return $basename;
	}

	$file  = nfd_sm_plugin_file();
	$guess = plugin_basename( $file );

	if ( file_exists( WP_PLUGIN_DIR . '/' . $guess ) ) {
		$basename = $guess;

		return $basename;
	}

	$basename = basename( dirname( $file ) ) . '/' . basename( $file );
	$real     = realpath( dirname( $file ) );
	$entries  = is_dir( WP_PLUGIN_DIR ) ? scandir( WP_PLUGIN_DIR ) : array();

	foreach ( (array) $entries as $entry ) {
		if ( '.' === $entry || '..' === $entry || ! is_dir( WP_PLUGIN_DIR . '/' . $entry ) ) {
			continue;
		}

		if ( false !== $real && realpath( WP_PLUGIN_DIR . '/' . $entry ) === $real ) {
			$basename = $entry . '/' . basename( $file );

			break;
		}
	}

	return $basename;
}

/**
 * URL for a file inside this plugin's directory.
 *
 * Worked out when it is asked for, from the path WordPress addresses this plugin by — never
 * baked into a constant as the plugin loads. `plugin_dir_url()` can only express a symlinked
 * plugin directory through `$wp_plugin_paths`, which `wp-settings.php` fills in as it loads the
 * *active* plugins; anything that includes this plugin earlier than that — the import's own
 * mu-plugin loader, a drop-in, `wp --require` — computes its URLs before that mapping exists
 * and gets the plugin's absolute filesystem path glued onto the plugins URL, so every asset
 * 404s and the admin page renders empty.
 *
 * Handing `plugins_url()` the path under `WP_PLUGIN_DIR` sidesteps the mapping altogether: it
 * is then a plain prefix strip, correct whoever loaded the plugin and whenever they did it.
 *
 * @param string $path Path relative to the plugin directory.
 *
 * @return string
 */
function nfd_sm_plugin_url( $path = '' ) {
	return plugins_url(
		ltrim( (string) $path, '/' ),
		rtrim( WP_PLUGIN_DIR, '/\\' ) . '/' . nfd_sm_plugin_basename()
	);
}

/**
 * This plugin's directory name inside the plugins directory.
 *
 * @return string
 */
function nfd_sm_plugin_dirname() {
	$basename = nfd_sm_plugin_basename();
	$slash    = strpos( $basename, '/' );

	return false === $slash ? $basename : substr( $basename, 0, $slash );
}
